### PR TITLE
update the documentation for "Using SwaggerUI with sbt-assembly"

### PR DESCRIPTION
**Pull request by Zhen-hao**
closing https://github.com/softwaremill/tapir/issues/2152

### CODE REVIEW

**Comment by adamw** [comment]
Thanks! I'm not sure what was the original problem, though - `MergeStrategy.first` should resolve build-time problems (where there are multiple resources with the same name), not run-time NPEs?

**Comment by Zhen-hao** [comment]
My problem was that the other rules discard all other `META-INF` files, including those in `resources`. 
I wasn't sure if `MergeStrategy.first` was the best option, but it was less restrictive than `singleOrError`.
I played safe. If you are certain `MergeStrategy.singleOrError` won't be a problem, we should use it.

**Comment by adamw** [comment]
Hm that's weird, no discarding should take place ... we only have special handling for `pom.properties` and otherwise we use the default (which I think is `deduplicate). You don't happen to have an example project where this can be reproduced?

**Comment by Zhen-hao** [comment]
I meant that our pre-existing merge rules were discarding all `META-INF` files. Hence, adding the `PathList("META-INF", "maven", "org.webjars", "swagger-ui", "pom.properties")` line alone wasn't enough.
Adding the second line would make it work in any possible existing project.

**Pull request closed without merging**
