### PR TITLE
Use operation id for endpoint name generation in codegen

### PR DESCRIPTION
**Pull request by hughsimpson**
After making https://github.com/softwaremill/tapir/pull/3059 it occurred to me that I wouldn't even have had the issue if tapir was using operationId to generate the endpoint name...

### CODE REVIEW

**Comment by adamw** [comment]
This makes sense - though there are some tests failing in `openapiCodegenCore2_12`

**Comment by hughsimpson** [comment]
Mea culpa - sorry about that, not sure how I missed those failing tests. Pushed fix now.

**Comment by adamw** [comment]
Thanks!

**Comment by hughsimpson** [comment]
You're more than welcome. I've been using Tapir since I saw your talk at ScalaWorld in... 2019? Very keen on the codegen stuff, so might have room to help more if the wind blows from the right direction

**Comment by adamw** [comment]
> You're more than welcome. I've been using Tapir since I saw your talk at ScalaWorld in... 2019? Very keen on the codegen stuff, so might have room to help more if the wind blows from the right direction

Great to hear :) The codegen module definitely needs a lot of work (there are quite a lot of issues with the codegen label, for example).

**Pull request merged**
