### PR TITLE
Add hidden flag for API parameters

### PR DESCRIPTION
**Pull request by slavaschmidt**

### CODE REVIEW

**Comment by adamw** [comment]
Thanks - I think I'd have three major comments here:
* I don't think `hidden` should be part of the schema - we want to hide/show entire inputs/outputs, not e.g. nested fields in a json body. So it's enough if this is part of `EndpointIO.Info`
* I'm not sure if `hidden` is the best name. Will people understand that this relates to documentation only? Maybe `hideInDocs`? 
* instead of modifying existing test cases, it's better to add new, dedicated ones. Otherwise we'll end up with hard-to-debug, complex test endpoint definitions

**Comment by slavaschmidt** [comment]
Thank you for the feedback! 
My motivation for the first point (modifying the `Schema` and not the `Info`) was that the RequestInterceptor can actually modify anything in different ways, including request body, for example adding new JSON blocks to it. I understand that this sounds like a corner case but it is still technically possible.

**Comment by adamw** [comment]
Hm well but in such a case you can provide a schema that doesn't contain these additional fields, and your codec (which actually does the deserialising) might deserialise to a data structure containing them. So you'd in effect omit such a field from the schema. Wouldn't that work?

**Comment by adamw** [comment]
One case where it wouldn't work is if you would want to add validation to such a field. Maybe indeed a hidden-schema field makes sense, similarly to a transient field in Java. Ok, let's try this route :)

**Comment by slavaschmidt** [comment]
I can't run tests in master branch with scala 2.12.14 and openjdk version "17.0.1" 2021-10-19 LTS. Could you please give me a hint how to fix that?

Compile errors I observe:

```
sbt testJVM_2_12

scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving trait EndpointSecurityInputsOps
[error] error while loading EndpointSecurityInputsMacros, class file '/Users/slasch/work/workspaces/personal/tapir/core/target/jvm-2.12/classes/sttp/tapir/macros/EndpointSecurityInputsMacros.class' is broken
[error] (class java.lang.RuntimeException/error reading Scala signature of EndpointSecurityInputsMacros.class: illegal cyclic reference involving trait EndpointSecurityInputsOps)
scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving trait EndpointInputsOps
[error] error while loading EndpointInputsMacros, class file '/Users/slasch/work/workspaces/personal/tapir/core/target/jvm-2.12/classes/sttp/tapir/macros/EndpointInputsMacros.class' is broken
[error] (class java.lang.RuntimeException/error reading Scala signature of EndpointInputsMacros.class: illegal cyclic reference involving trait EndpointInputsOps)
scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving trait EndpointErrorOutputsOps
[error] error while loading EndpointErrorOutputsMacros, class file '/Users/slasch/work/workspaces/personal/tapir/core/target/jvm-2.12/classes/sttp/tapir/macros/EndpointErrorOutputsMacros.class' is broken
[error] (class java.lang.RuntimeException/error reading Scala signature of EndpointErrorOutputsMacros.class: illegal cyclic reference involving trait EndpointErrorOutputsOps)
scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving trait EndpointOutputsOps
[error] error while loading EndpointOutputsMacros, class file '/Users/slasch/work/workspaces/personal/tapir/core/target/jvm-2.12/classes/sttp/tapir/macros/EndpointOutputsMacros.class' is broken
[error] (class java.lang.RuntimeException/error reading Scala signature of EndpointOutputsMacros.class: illegal cyclic reference involving trait EndpointOutputsOps)
scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving trait EndpointTransput
[error] error while loading EndpointTransputMacros, class file '/Users/slasch/work/workspaces/personal/tapir/core/target/jvm-2.12/classes/sttp/tapir/macros/EndpointTransputMacros.class' is broken
[error] (class java.lang.RuntimeException/error reading Scala signature of EndpointTransputMacros.class: illegal cyclic reference involving trait EndpointTransput)


sbt testDocs

[error] /Users/slasch/work/workspaces/personal/tapir/core/src/main/scala/sttp/tapir/EndpointIO.scala:10:19: encountered unrecoverable cycle resolving import.
[error] Note: this is often due in part to a class depending on a definition nested within its companion.
[error] If applicable, you may wish to try moving some members into another object.
[error] import sttp.tapir.macros.{EndpointInputMacros, EndpointOutputMacros, EndpointTransputMacros}
[error]                   ^
[error] /Users/slasch/work/workspaces/personal/tapir/core/src/main/scala/sttp/tapir/EndpointIO.scala:10:19: encountered unrecoverable cycle resolving import.
[error] Note: this is often due in part to a class depending on a definition nested within its companion.
[error] If applicable, you may wish to try moving some members into another object.
[error] import sttp.tapir.macros.{EndpointInputMacros, EndpointOutputMacros, EndpointTransputMacros}
[error]                   ^
[error] /Users/slasch/work/workspaces/personal/tapir/core/src/main/scala/sttp/tapir/EndpointIO.scala:47:42: not found: type EndpointTransputMacros
[error] sealed trait EndpointTransput[T] extends EndpointTransputMacros[T] {
[error]                                          ^
[error] /Users/slasch/work/workspaces/personal/tapir/core/src/main/scala/sttp/tapir/EndpointIO.scala:47:42: not found: type EndpointTransputMacros
[error] sealed trait EndpointTransput[T] extends EndpointTransputMacros[T] {
[error]                                          ^
[error] /Users/slasch/work/workspaces/personal/tapir/core/src/main/scala/sttp/tapir/Endpoint.scala:10:19: encountered unrecoverable cycle resolving import.
[error] Note: this is often due in part to a class depending on a definition nested within its companion.
[error] If applicable, you may wish to try moving some members into another object.
[error] import sttp.tapir.macros.{EndpointErrorOutputsMacros, EndpointInputsMacros, EndpointOutputsMacros, EndpointSecurityInputsMacros}
[error]                   ^
[error] /Users/slasch/work/workspaces/personal/tapir/core/src/main/scala/sttp/tapir/Endpoint.scala:144:55: not found: type EndpointErrorOutputsMacros
[error] trait EndpointErrorOutputsOps[A, I, E, O, -R] extends EndpointErrorOutputsMacros[A, I, E, O, R] {
[error]                                                       ^
[error] /Users/slasch/work/workspaces/personal/tapir/core/src/main/scala/sttp/tapir/Endpoint.scala:104:49: not found: type EndpointInputsMacros
[error] trait EndpointInputsOps[A, I, E, O, -R] extends EndpointInputsMacros[A, I, E, O, R] {
[error]                                                 ^
[error] /Users/slasch/work/workspaces/personal/tapir/core/src/main/scala/sttp/tapir/Endpoint.scala:247:50: not found: type EndpointOutputsMacros
[error] trait EndpointOutputsOps[A, I, E, O, -R] extends EndpointOutputsMacros[A, I, E, O, R] {
[error]                                                  ^
[error] /Users/slasch/work/workspaces/personal/tapir/core/src/main/scala/sttp/tapir/Endpoint.scala:83:57: not found: type EndpointSecurityInputsMacros
[error] trait EndpointSecurityInputsOps[A, I, E, O, -R] extends EndpointSecurityInputsMacros[A, I, E, O, R] {
[error]
```

**Comment by adamw** [comment]
@slavaschmidt yeah that's some problem in the scala compiler, can you try first running `clean`?

**Pull request closed without merging**
