### PR TITLE
Upgrade zhttp from 1.0.0.0-RC25 to 1.0.0.0-RC27

### PR DESCRIPTION
**Pull request by strokyl**

### CODE REVIEW

**Comment by adamw** [comment]
Thanks!

**Comment by strokyl** [comment]
Thank you for the fast review/merge @adamw!
Do you think it would be possible to release a `v0.20.2`?

**Comment by adamw** [comment]
Yes, the release is in progress: https://github.com/softwaremill/tapir/actions/runs/2343589038

**Comment by adamw** [comment]
And done :)

**Pull request merged**
