### PR TITLE
Add option to provide custom WS config in zio-http

### PR DESCRIPTION
**Pull request by kyri-petrou**
Attempt at #3290.

@adamw I'm not sure what would be the best way to test these changes, do you have any suggestions? Also, the addition of the argument in `ZioHttpServerOptions` makes this a breaking change. Should we add the default value to the constructor of `ZioHttpServerOptions` to make it at least source compatible?

### CODE REVIEW

**Comment by adamw** [comment]
We don't have any compatibility requirements for this module (see https://tapir.softwaremill.com/en/latest/stability.html).

That's especially true for zio-http - every release (RC or not) usually means a major rewrite of the source code ;)

**Comment by adamw** [comment]
Which is to say: it's not a problem to add new options

**Comment by kyri-petrou** [comment]
> We don't have any compatibility requirements for this module (see https://tapir.softwaremill.com/en/latest/stability.html).
> 
> That's especially true for zio-http - every release (RC or not) usually means a major rewrite of the source code ;)

Ah nice, wasn't aware of this - that's good to know!

**Comment by kyri-petrou** [comment]
@adamw tests for Scala 3 seem to be failing but I'm not entirely sure why. Any chance that's due to test flakyness?

**Comment by adamw** [comment]
Thanks :) Indeed, seems the test was flaky

**Pull request merged**
