### PR TITLE
Generate schema for map

### PR DESCRIPTION
**Pull request by ghostbuster91**
As discussed in #62

### CODE REVIEW

**Comment by adamw** [comment]
Just to verify: the schema we want to generate for a map is just `type: object`? (looking at https://swagger.io/specification/#schemaObject, it seems so).

If so, maybe this is just a matter of:

```
implicit val schemaForMap: SchemaFor[Map[K, V]] = SchemaFor(SObject("Map"))
```

?

**Comment by ghostbuster91** [comment]
I thought that you want to distinguish between different maps in openApi docs.

**Comment by adamw** [comment]
I don't know what I wanted ;) But looking at the tests - does it make sense to make this distinction?

**Comment by ghostbuster91** [comment]
Still it was fun as always to play with some macros :)

**Comment by adamw** [comment]
It's always fun ;)

**Pull request merged**
