### PR TITLE
make reject handler effectful

### PR DESCRIPTION
**Pull request by danielleontiev**
Follow up for https://github.com/softwaremill/tapir/pull/2001 - making RejectHandler effectful

### CODE REVIEW

**Comment by adamw** [comment]
Thanks!

**Comment by danielleontiev** [comment]
Do you think `DecodeFailureHandler` should become effectful too for consistency?

**Comment by adamw** [comment]
Only if there's a use-case for it :)

**Comment by danielleontiev** [comment]
I do not have such use case personally but can imagine something like recording active metrics or logging on each stage of request processing. What do you think?

**Comment by adamw** [comment]
Hm I think such logging/metrics would be best served by separate intereptors. The DFH is complex enough, so let's leave it as-is

**Comment by danielleontiev** [comment]
Ok, thank you!

**Pull request merged**
