### PR TITLE
feat(zio): support Native

### LINKED ISSUE #4013: Feat: support zio and zio-prelude for Native
I will work on this when softwaremill/sttp-shared#435 is merged

Will also add 2.12 and 2.13 zio-json support for Scala Native

With ZServerEndpoint support for Scala Native https://github.com/lolgab/snunit can start supporting Tapir ZIO

### PR DESCRIPTION
**Pull request by ThijsBroersen**
closes #4013

### CODE REVIEW

**Comment by ThijsBroersen** [comment]
The Native 2.12 and 2.13 are not in the CI list

**Comment by ThijsBroersen** [comment]
there is a test failure (timeout), flaky? Or related to new dependencies?

**Comment by adamw** [comment]
Let's see :)

**Comment by adamw** [comment]
Sometimes the ZIO tests hang ;) but we didn't manage to find the root cause yet

**Comment by adamw** [comment]
Thanks! :)

**Pull request merged**
