### PR TITLE
Scala Native support for http4sServer

### PR DESCRIPTION
**Pull request by fede0664**
* Added nativePlatform to http4sServer in build.sbt 
* http4sServer tests run only on jvm
* Moved log4s dependency on Http4sServerInterpreter to jvm specific code
* Implemented DefaultServerLog builder for native using simple printlns

### CODE REVIEW

**Comment by adamw** [comment]
I suspect that compiling the server tests for scala native poses some problems?

**Comment by fede0664** [comment]
Correct, serverTests depend on softwaremill/common/tagging and softwaremill/tappir/sttpClient that are not available on Native yet. Tagging looks simple to resolve. I'm looking at what's needed for sttpClient.

**Comment by adamw** [comment]
FWIW, I've published tagging 2.3.4 for native

**Comment by adamw** [comment]
Let's merge this and if you manage to make any progress on the tests, please create a separate PR :)

**Pull request merged**
