### PR TITLE
Changed type parameter of VertxZioServerOptions from F[_] to R of RIO[R, *] interop effect type, added widen method.

### PR DESCRIPTION
**Pull request by Grryum**
I noticed some changes in #3011 which I would like to use. And decided to make the same changes to VertxZioServerOptions also. Hope there would be no problem with backward compatibility.

### CODE REVIEW

**Comment by Grryum** [comment]
I have prepared same changed for zio1, would it be ok to push it also?

**Comment by adamw** [comment]
@Grryum sure! :)

**Comment by Grryum** [comment]
@adamw finally done :)

**Comment by adamw** [comment]
Thanks! :)

**Pull request merged**
