### PR TITLE
added ability to override server for endpoint

### PR DESCRIPTION
**Pull request by payurgin**
Fix https://github.com/softwaremill/tapir/issues/648

### CODE REVIEW

**Comment by adamw** [comment]
Thanks for the PR!

I'm a bit on the fence on the change, as I'm not sure how much meta-data should be pull into `EndpointInfo`, vs. the ability to modify the `OpenAPI` object.

Name/description seem general enough, but servers & server variables are quite specific to openapi, and creating yet another copy of the openapi model in `EndpointInfo` is suspicious. So on one hand, it seems this functionality should belong to the `openapi` module. On the other, looking up individual endpoints in the `OpenAPI` object *after* they've been interpreted as docs is cumbersome.

**Comment by payurgin** [comment]
I'm understand you points. 
I see one more good point: we probably can use that servers with variables for client generation :)
But in general I agree with you about negative consequences of such changes.

**Comment by adamw** [comment]
Sorry this takes so long, but I still have a feeling that this should rather belong to the `OpenAPI` class. That's how you specify the default servers  - for all endpoints which don't have specific servers set.

Maybe a good compromise would be for the `TapirOpenAPIDocs` interpreter to add an extension method to `OpenAPI`, which would allow setting the servers for an `Endpoint`. Sth like: `openApi.endpointServers(endpoint, servers)`. The method would have to do some reverse-engineering, that is match the generated path with `FixedPath`/`PathCaptures`.

Or maybe yet another way - pass in the additional information to the `.toOpenAPI` method. Now it only takes the `Info` object, but maybe it could also accept a `Map[Endpoint, Servers]`? That way we would avoid the reverse-engineering. So this might be the best option. What do you think?

**Comment by adamw** [comment]
Closing as this can be done if needed using an `Attribute` & extension methods -see `DocsExtensionAttribute` as an example https://tapir.softwaremill.com/en/latest/docs/openapi.html#openapi-specification-extensions

**Pull request closed without merging**
