### PR TITLE
Compile sttp client for ScalaJS

### PR DESCRIPTION
**Pull request by nadenf**
This time with just support for ScalaJS.

### CODE REVIEW

**Comment by adamw** [comment]
Still, the JS version doesn't compile - some code changes would be needed I think

**Comment by baank** [comment]
@adamw .. It seemed to pass on TravisCI:
https://travis-ci.org/softwaremill/tapir/builds/573734972

Is this when you run it locally .. and is there an error message ?

**Comment by adamw** [comment]
It passes on travis as you only aggregate the jvm project. Try adding `core.js` to the aggregates, or switching to the `coreJS` project in the sbt console

**Comment by baank** [comment]
@adamw .. Bit confused. So I ran "sbt", then "project coreJS" and then "test". And no errors.

**Comment by adamw** [comment]
Hmm I had lots, that's weird :) Can you try adding `core.js` to the list of aggregate projects, so that it is built by travis as well?

**Comment by baank** [comment]
@adamw .. Done. Not sure how to get Travis to build it though.

**Comment by adamw** [comment]
@baank I think you'll first have to update to latest `master` as there are some conflicts which need to be resolved. Then the travis build should start

**Comment by adamw** [comment]
@Truji92 you are welcome to join :) however I think this will be more work than the above

**Comment by dpfeiffer** [comment]
We just saw that there is already an open PR for #98 . We just opened one which is more or less based on this but is on the latest `master`. More information can be found in #351

**Comment by adamw** [comment]
Superseded by #815

**Pull request closed without merging**
