### PR TITLE
feat: Add zio-http multipart body support

### LINKED ISSUE #2518: Request hanging on multipartBody file uploads with zio-http
Tapir version: 1.1.3

Scala version: 2.13.10

I'm defining the endpoint and server logic like this:
```scala
  import sttp.tapir.ztapir._
  import sttp.tapir.generic.auto._
  import io.circe.generic.auto._
  import sttp.tapir.json.circe._

  case class UploadForm(file: Part[TapirFile])

  val uploadEndpoint: PublicEndpoint[
    UploadForm,
    String,
    String,
    Any
  ] = endpoint
    .post
    .in("files")
    .in(multipartBody[UploadForm])
    .errorOut(stringBody)
    .out(stringBody)
    .name("test files endpoint here")

  val uploadServerEndpoint =
    uploadEndpoint
      .zServerLogic[Any] { x =>
        (for {
          _ <- ZIO.succeed(logger.info(s">>>>>>>>>>>>> $x"))
        } yield "ooooops")
      }
```

then making zio-http server:
```scala
    val zserverLog: ServerLog[Task] = DefaultServerLog(
        doLogWhenReceived = { s => ZIO.succeed(logger.info(s">>> $s")) },
        doLogWhenHandled = { case (s, e) => ZIO.succeed(logger.info(s">>> $s: $e")) },
        doLogAllDecodeFailures = { case (s, e) => ZIO.succeed(logger.info(s">>> $s: $e")) },
        doLogExceptions = { case (s, e) => ZIO.succeed(logger.info(s">>> $s: $e")) },
        noLog = ZIO.succeed(logger.info(".........................")),
        logWhenReceived = true,
        logWhenHandled = true,
        logAllDecodeFailures = true
      )

      val zserverOpts = ZioHttpServerOptions
        .customiseInterceptors
        .serverLog(log = zserverLog)
        .options

      val fsR = ZioHttpInterpreter(zserverOpts).toHttp(List(uploadServerEndpoint))

     Unsafe.unsafe(implicit u =>
        runtime
          .unsafe
          .runToFuture(
            Server.start(8081, fsR)
          )
      )
```

Then starting the server and uploading a file with curl command:
```shell
% curl http://localhost:8081/files \
     -X POST \
     -F 'file=@build.sbt' \
     -v --max-time 10 --no-keepalive
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:8081...
* Connected to localhost (127.0.0.1) port 8081 (#0)
> POST /files HTTP/1.1
> Host: localhost:8081
> User-Agent: curl/7.79.1
> Accept: */*
> Content-Length: 12006
> Content-Type: multipart/form-data; boundary=------------------------7022269a28a25ad5
>
* We are completely uploaded and fine
* Operation timed out after 10005 milliseconds with 0 bytes received
* Closing connection 0
curl: (28) Operation timed out after 10005 milliseconds with 0 bytes received
%
```

Server logs only this:
```
[info] INFO  [nioEventLoopGroup-2-3] - >>> Request received: POST /files
```

And curl times out not receiving anything.

### PR DESCRIPTION
**Pull request by seakayone**
Resolves #2518

Currently tests fail because the incoming ServerRequest contains the multiple parts, but when calling zio.http.Request.body.[asMultipartFormStream|asMultiPartForm] they only ever return the single, first part. 

Seems to be a bug in zio-http: https://github.com/zio/zio-http/issues/2411

Bug was fixed and released. I have let the build run in my own actions and it succeded: https://github.com/seakayone/tapir/actions/runs/9943391610

### CODE REVIEW

**Comment by godspeedelbow** [comment]
@seakayone now that https://github.com/softwaremill/tapir/pull/3690 is merged, can you put up this PR for review?

**Comment by seakayone** [comment]
I am planning to finalize this PR in the next couple of days hopefully.

**Comment by adamw** [comment]
There's some problems updating ZIO, I think we'll need to first tackle https://github.com/softwaremill/tapir/pull/3876/, and then get back to this PR. Sorry for the problems :)

**Comment by adamw** [comment]
Found the problem in zio-http: https://github.com/zio/zio-http/issues/2977

**Comment by alexander-klimov** [comment]
Hello.
Any news on this one and #3876 ?
Really eager to start using multipart requests -_-

**Comment by resilica** [comment]
@adamw Is there anything blocking for this to be merged? The underlying bugs are resolved and we are waiting for this fix. Thanks!

**Comment by geeeezmo** [comment]
> @adamw Is there anything blocking for this to be merged? The underlying bugs are resolved and we are waiting for this fix. Thanks!

I'm guessing it's the [same reason](https://github.com/softwaremill/tapir/pull/3876#issuecomment-2295577209)

**Comment by adamw** [comment]
@resilica @geeeezmo yes, unfortunately RC9 had a bug which prevented the update, there's another one now in RC10.

**Comment by alexander-klimov** [comment]
@seakayone can this PR be made public so it can be reviewed?

**Comment by alexander-klimov** [comment]
Thank you, Adam, for all the work you do.
Can't wait for the next release 🙃

**Comment by seakayone** [comment]
@adamw Thanks for finalizing this.

**Pull request merged**
