### PR TITLE
Add support for grpc repeated  and oneof fields

### PR DESCRIPTION
**Pull request by mbore**
Closes https://github.com/softwaremill/tapir/issues/2524 https://github.com/softwaremill/tapir/issues/2525

### CODE REVIEW

**Comment by adamw** [comment]
Shouldn't the list of supported features be somehow mentioned in the docs? Or an example provided? Otherwise people will have trouble discovering what works, and what doesn't

**Comment by mbore** [comment]
right, good point. I will update the example and add some docs

**Comment by mbore** [comment]
I add a list of supported features. An extended example I'd like to prepare as a separate PR (I'd like to use it in a blog post)

**Comment by adamw** [comment]
Thanks :)

**Pull request merged**
