### PR TITLE
Use custom validator message in DecodeFailureHandler

### PR DESCRIPTION
**Pull request by rwiskerke**
related to https://github.com/softwaremill/tapir/issues/2329#issuecomment-1195321792

### CODE REVIEW

**Comment by adamw** [comment]
Thanks! Though doesn't the `ve.customMessage match` in line 236 (https://github.com/softwaremill/tapir/blob/380accd82369ca6eb978740ce24684dd43d5258f/server/core/src/main/scala/sttp/tapir/server/interceptor/decodefailure/DecodeFailureHandler.scala#L237) handle this already?

**Comment by rwiskerke** [comment]
> Thanks! Though doesn't the `ve.customMessage match` in line 236 (
> 
> https://github.com/softwaremill/tapir/blob/380accd82369ca6eb978740ce24684dd43d5258f/server/core/src/main/scala/sttp/tapir/server/interceptor/decodefailure/DecodeFailureHandler.scala#L237
> ) handle this already?

No, Validator.Custom#showMessage is currently not mapped to `ValidationError#customMessage`, but that is also a way to handle this.

**Comment by adamw** [comment]
🤦 I'm very sorry I mislead you; `showMessage` is used for the `show(Validator)` method, which is used to create a string representation of the validator object; custom messages are supported via `ValidatorResult.Invalid(customMessage)` - and that's how they should be reported. Sorry again!

**Comment by rwiskerke** [comment]
@adamw That's fine, that just means I shouldn't use `ValidationResult.validWhen` in my `Validator.custom` implementation, but create the `ValidatorResult.Invalid(..)` myself 👍

**Pull request closed without merging**
