### PR TITLE
zio-http multipart support

### PR DESCRIPTION
**Pull request by lvitaly**
https://github.com/softwaremill/tapir/issues/2518
https://github.com/softwaremill/tapir/issues/1595

### CODE REVIEW

**Comment by zeffd** [comment]
Hello, thanks for the effort in this
I know It's is in draft mode, but I tried to add your changes and tested.
For smaller files (~50-60KB) it works fine but for more it gives 413 (Request Entity Too Large).
So is that the reason you have it in draft more (And you are trying to resolve this) OR there is some more stuff that i am unaware of ?

**Comment by geeeezmo** [comment]
> 

That might be the default streaming request size of `zio-http` server (100 KB).
You can change it via `Server.Config` (see [here](https://github.com/zio/zio-http/blob/eea2a6bdb59d65ee72d6a16880155816232046f5/zio-http/src/main/scala/zio/http/Server.scala#L154))

**Comment by geeeezmo** [comment]
Also, would be great for this PR to gain some traction as this is a much needed feature :)

**Comment by zeffd** [comment]
> @zeffd That might be the default streaming request size of `zio-http` server (100 KB). You can change it via `Server.Config` (see [here](https://github.com/zio/zio-http/blob/eea2a6bdb59d65ee72d6a16880155816232046f5/zio-http/src/main/scala/zio/http/Server.scala#L154))

Yes thanks it works now 👍

**Comment by lvitaly** [comment]
@zeffd, unfortunately, this is a naive implementation of the multipart. It works correctly for file upload, but tests for multipart forms fail with status code 400. I need to figure out what's wrong there.

**Comment by adamw** [comment]
Closing old PRs

**Comment by geeeezmo** [comment]
Has this been already implemented in another PR?

**Comment by adamw** [comment]
@geeeezmo no, multipart support is still lacking for zio http. Though zio http APIs change so much that I suppose you'd need to start from scratch anyway ;)

**Pull request closed without merging**
