### PR TITLE
Allow to retrieve schema type parameters full name

### PR DESCRIPTION
**Pull request by yakivy**
https://github.com/softwaremill/tapir/issues/3463

### CODE REVIEW

**Comment by kciesielski** [comment]
One question regarding the issue report:
> Specifically Value[A.B] and Value[B.B] produce the same Schema.SName that causes a conflict in the docs components

Wouldn't that produce `Value_B1` and `Value_B2`?
Besides, I would expect this PR to require changes in tests like this one
https://github.com/softwaremill/tapir/blob/master/docs/openapi-docs/src/test/scalajvm/sttp/tapir/docs/openapi/VerifyYamlTest.scala#L254

but they still pass, so maybe I don't understand well what really is affected?

**Comment by yakivy** [comment]
hey @kciesielski , this PR only puts full type name into the Schema.SName.typeParameterShortNames so you can use them in the custom schema mappers, all other logic is kept backward compatible. For example default schema name mapper still takes only last symbol name:
https://github.com/softwaremill/tapir/pull/3500/files#diff-8a362583486937e726273911ac38096a6d5037ac832a634d021c55297ce6bfacR8

**Comment by kciesielski** [comment]
I see, thank you for clarifying!

**Review by kciesielski — APPROVED** [review]

**Comment by adamw** [comment]
Thanks! :) One small question - maybe it would make sense to add a test, which shows that you can customise the schema naming, fixing the original problem from #3463?

**Comment by adamw** [comment]
Thanks :)

**Pull request merged**
