### PR TITLE
Add cats module with instances for SchemaFor

### PR DESCRIPTION
**Pull request by implmnt**
This PR adds a new module "tapir-cats" for some cats integrations. Initially it contains SchemaFor instances for NonEmptyList, NonEmptyChain and NonEmptySet.

### CODE REVIEW

**Comment by adamw** [comment]
Released in 0.11.8, thanks!

**Comment by implmnt** [comment]
> Released in 0.11.8, thanks!

My apologies. I forgot to highlight the case of collision with cats library.

There is a problem with package name `tapir.cats.*`. It clashes with `cats` when `tapir._` is imported.

We could rename `tapir.cats` to `tapir.catz` or use some intermediate word in FQN(e.g. `tapir.foo.cats`). The last one should resolve conflicts in most common case when `tapir._` is imported.

**Comment by adamw** [comment]
I think an intermedia word would be best. The module provides integration for cats datatypes, to derive codecs. So maybe `tapir.data.cats` or `tapir.codec.cats` ?

**Comment by implmnt** [comment]
Yes, `tapir.codec.cats` looks good! 
Gonna do another PR to fix this.

**Pull request merged**
