### PR TITLE
Renamed NettyId to NettySync

### LINKED ISSUE #3625: Rename NettyIdServer to NettySyncServer
Or maybe simply `NettyServer` & `NettyServerInterpreter`?

### PR DESCRIPTION
**Pull request by Pask423**
closes #3625

### CODE REVIEW

**Comment by adamw** [comment]
Thanks!

@kciesielski @lbialy what do you think, how should we call the synchronouse variants of tapir interpreters / sttp client backends? For reference:
* they use the `Id` "effect" type
* in sttp client, we currently have e.g. `DefaultSyncBackend`, `HttpClientSyncBackend`
* for `Future`s, we have `NettyFutureServer`, `HttpClientFutureBackend`; for CE, `NettyCatsServer`, `HttpClientCatsBackend`
* hence here propose also `NettySyncServer`
* alternatively, we can go with simply `NettyServer` and `HttpClientBackend`

opinions? :)

**Comment by lbialy** [comment]
While NettyServer sounds good and reminds me of time ten years ago when you
had SomethingServer and maybe, at most, an AsyncSomethingServer, we have so
many variants now that lack of prefix is rather confusing instead of
immediately understandable. Therefore my vote is on NettySyncServer because
now, in Scala, given the amount of competing approaches, sync is just one
option. I imagine with caprese/gears we'll have another variant with
capability types annotations and it will also be sync so there's possible
future ambiguity on "sync" term too :)

**Comment by kciesielski** [comment]
+1 to @lbialy :)

**Comment by adamw** [comment]
Ok, thanks for your input :)

**Pull request merged**
