### PR TITLE
Improve ergonomics of encode-to-raw function for validators, inferring when possible and providing methods to specify using in-scope codecs

### LINKED ISSUE #1398: Tapir OpenApi YAML drops enum validation for arrays
Endpoint
```scala
val getEnums = endpoint.get
    .in("enums")
    .in(query[Int]("n").validate(Validator.enumeration(List(1, 2))))
    .in(query[List[Int]]("ns").validateIterable(Validator.enumeration(List(1, 2))))
    .out(stringBody)
```
generates the following OpenAPI YAML:
```yaml
get:
      operationId: getEnums
      parameters:
      - name: n
        in: query
        required: true
        schema:
          type: integer
          enum:
          - 1
          - 2
      - name: ns
        in: query
        required: false
        schema:
          type: array
          items:
            type: integer
```

instead of
```yaml
get:
      operationId: getEnums
      parameters:
      - name: n
        in: query
        required: true
        schema:
          type: integer
          enum:
          - 1
          - 2
      - name: ns
        in: query
        required: false
        schema:
          type: array
          items:
            type: integer
            enum:
            - 1
            - 2
```

### PR DESCRIPTION
**Pull request by adamw**
Closes #1398

### CODE REVIEW

**Comment by adamw** [comment]
@kamilkloch see if this looks right to you

**Comment by kamilkloch** [comment]
@adamw Thanks for picking this up! I tried to fix it myself but got lost in the code.
```scala
    case class A()
    implicit val aPlainCodec: Codec.PlainCodec[A] = Codec.string.map(_ => A())(_ => "AA")

    val getEnums = endpoint.get
      .in("enums")
      .in(query[A]("a").validate(Validator.enumeration(List(A()))))
      .in(query[List[A]]("as").validateIterable(Validator.enumeration(List(A()))))
      .out(stringBody)
```
produces
```yaml
openapi: 3.0.3
info:
  title: Fruits
  version: '1.0'
paths:
  /enums:
    get:
      operationId: getEnums
      parameters:
      - name: a
        in: query
        required: true
        schema:
          type: string
          enum:
          - A()
      - name: as
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
      responses:
        '200':
          description: ''
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: 'Invalid value for: query parameter a, Invalid value for: query
            parameter as'
          content:
            text/plain:
              schema:
                type: string
```

First, enumeration is missing for `as`.

Second, for `a` we get
```yaml
enum:
  - A()
```
I would expect
```yaml
enum:
  - AA
```

What do you think?

**Comment by adamw** [comment]
The problem is that we don't know how to encode values of arbitrary types into a "raw" form, which could be rendered in documentation.

In the example: `query[List[A]]("as").validateIterable(Validator.enumeration(List(A())))`, we only have a `PlainCodec[List[A]]`, but we don't have a codec for `A`. Codecs are opaque and don't have a recursive inspectable structure, so we can't get the `A`-codec from a `List[A]`-codec.

That's why `Validator.enumeration` has another variant, which adds the `encodeToRaw` parameter, which allows specifying, how data should be encoded. The fix in this PR is to infer this parameter (if not explicitly provided) for known "basic" types such as numbers.

Another way to attempt to fix this would be to require an implicit codec when calling `Validator.enumeration` and using it to create the `encodeToRaw` function (which is basically a function `T => Any`). However, this wouldn't be that user-friendly as well - the user would have to explicitly specify the codec format which should be used, as we don't know (when calling `Validator.enumeration`) if we need a plain text codec, or a json codec, or something else. 

Alternatively, we could add a `Validator.plainEnumeration` which would require a `Codec[String, T, TextPlain]`. Or, next to the existing `.encode` method, we could add a `.encodeWithCodec[CodecFormat]` and `.encodeWithPlainCodec`.

What do you think?

**Comment by adamw** [comment]
@kamilkloch sorry forgot to mention you ^ :)

**Comment by kamilkloch** [comment]
@adamw `encodeToRaw` does the job indeed. Seems a bit unclean, though :)
`Validator.plainEnumeration[T: Codec.PlainCodec]` is a nice idea, if it does add too much noise. 

I experimented with adding a validator directly into Codec, and noticed some interesting behaviour:
```scala
    sealed trait T
    case object A extends T
    case object B extends T

    implicit val tPlainCodec: Codec.PlainCodec[T] = Codec.string.mapDecode {
      case "AA" => DecodeResult.Value[T](A)
      case "BB" => DecodeResult.Value[T](B)
      case _ => DecodeResult.Missing
    }{
      case A => "AA"
      case B => "BB"
    }
      .validate(Validator.enumeration(List(A, B)))

    val getEnums = endpoint.get
      .in("enums")
      .in(query[T]("t1")) // enum: - AA - BB (codec validator applied)
      .in(query[T]("t2")
        .validate(Validator.enumeration(List(A))) // enum: - A (query validator applied, codec validator ignored)
      )
      .in(query[List[T]]("ts")
        .validateIterable(Validator.enumeration(List[T](A))) // enum: - AA - BB (query validator ignored, codec validator applied)
      )
      .out(stringBody)
```
```yaml
- name: t1
        in: query
        required: true
        schema:
          type: string
          enum:
          - AA
          - BB
      - name: t2
        in: query
        required: true
        schema:
          type: string
          enum:
          - A
      - name: ts
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
            enum:
            - AA
            - BB
```
The outcome for `ts` is a bit misleading.

**Comment by adamw** [comment]
@kamilkloch Yes, I'm not a fan of `encodeToRaw` as well, but I don't know of a better solution given the current `Codec` design (which allows integrating with arbitrary encoding/decoding functions, without knowing the structure of the data).

Actually, I'm leaning towards having `Validator.enumeration(a, b, c).encodeWithPlainCodec` (+ docs), as `Validator.plainEnumeration` might suggest that there's something "plain" about the enumeration itself, while this only applies to how the enumeration is rendered in the docs.

Adding two enumeration validators is something that indeed might not work, I think the behavior can be considered non-determinstic. But that's a separate issue - please report if that's something that is causing you trouble.

**Comment by kamilkloch** [comment]
@adamw `Validator.enumeration(a, b, c).encodeWithPlainCodec` is also a nice solution :)

**Comment by adamw** [comment]
@kamilkloch see now :)

**Comment by kamilkloch** [comment]
@adamw What can I say, perfect. ;) Thank you!

**Pull request merged**
