### PR TITLE
Fix for update/zhttp 2.0.0 rc11

### PR DESCRIPTION
**Pull request by micsza**

### CODE REVIEW

**Comment by adamw** [comment]
Waiting for https://github.com/dream11/zio-http/issues/1421

**Comment by rators** [comment]
> Waiting for [zio/zio-http#1421](https://github.com/zio/zio-http/issues/1421)

1421 has been resolved as a result of https://github.com/zio/zio-http/pull/1409 being merged in.

**Comment by adamw** [comment]
@rators yes, now we're waiting for a release with the fix :)

**Comment by rators** [comment]
> @rators yes, now we're waiting for a release with the fix :)

Awesome! Thank you very much for your work on this issue @adamw. Will stay on zio-http RC-10 and I'll keep an eye on this PR in the meantime. 🙇

**Comment by frekw** [comment]
Would it be possible to have a release against a snapshot version of zio-http instead since there isn't an RC available at this time? There's been some quite important fixes since RC10 (like https://github.com/zio/zio-http/pull/1379) which makes it somewhat unusable for a lot of usecases as is :(

**Comment by adamw** [comment]
@frekw Sorry, we can't release using a snapshot version. We have to wait for something that's at least semi-stable :)

**Comment by nsmnds** [comment]
Any updates on this one? The current RC-10 is quite unusable because of https://github.com/zio/zio-http/pull/1379

**Comment by adamw** [comment]
@nsmnds I think it's a question for the ZIO HTTP team. There's no release yet, and we can't use RC11 as it's broken in another way.

**Comment by onsoup42** [comment]
There is now a new release of zhttp
https://github.com/zio/zio-http/releases/tag/v0.0.2

**Comment by frekw** [comment]
No artifacts are available yet though. :(

**Comment by adamw** [comment]
Yes only 0.0.1: https://repo1.maven.org/maven2/dev/zio/zio-http_3/

Though is that an "official" release, that is one which should be used? We just jumped from 2.0.0-RCsomething to 0.0.2 ;)

**Comment by frekw** [comment]
> Though is that an "official" release, that is one which should be used? We just jumped from 2.0.0-RCsomething to 0.0.2 ;)

I think it is until they iron everything for 1.0.0 out. But unfortunately 0.0.1 doesn't work because it's missing a package (`zio-http-logging`). :(

**Comment by frekw** [comment]
But there's a meta-ticket for 1.0 here: https://github.com/zio/zio-http/issues/1532

**Comment by frekw** [comment]
zio-http 0.0.3 has been [released](https://github.com/zio/zio-http/releases/tag/v0.0.3). I attempted an upgrade here: https://github.com/frekw/tapir/tree/chore/zio-http-0.0.3 but can't figure out what I'm doing wrong in order to get the tests running. :/

**Comment by frekw** [comment]
Hopefully I figured everything out, https://github.com/softwaremill/tapir/pull/2576

**Pull request closed without merging**
