### PR TITLE
fix: increase the adopt-tapir iframe's height

### PR DESCRIPTION
**Pull request by geminicaprograms**
So that one doesn't have scroll to see `Reset` and `Generate ZIP` buttons.

### CODE REVIEW

**Comment by adamw** [comment]
Hm where do you see the scroll? Looks fine here :)

**Comment by geminicaprograms** [comment]
> 

There is no scroll but no `Reset` or `generate ZIP` buttons either:
image

Scroll shows up once one hovers over the form are and scrolls up/down...

**Comment by adamw** [comment]
Is this on https://adopt-tapir.softwaremill.com? I've got a different header and everything scales nicely ;)

image

**Comment by adamw** [comment]
Ok, nevermind ;)

**Pull request merged**
