### PR TITLE
use remoteAddress from zio-http Request

### PR DESCRIPTION
**Pull request by dcihnaelsah**
Set connectionInfo.remote correctly to zio-http's request.remoteAddress

### CODE REVIEW

**Comment by adamw** [comment]
Thanks! Unfortunately it seems there are some compilation errors

**Comment by dcihnaelsah** [comment]
@adamw - overlooked the type, latest commit should return expected return type

**Comment by dcihnaelsah** [comment]
Tests for `3, Native` pass locally though.

**Comment by adamw** [comment]
Yeah the 3/native tests are flaky. Thanks :)

**Pull request merged**
