### PR TITLE
Upgrade to zio 2.0.0-RC5, zio http to 2.0.0-RC7

### PR DESCRIPTION
**Pull request by gavares**

### CODE REVIEW

**Comment by adamw** [comment]
I'm afraid the given memory setting will cause a container out of memory (killing the process), as the VMs that github actions give us have 7GB RAM total. So the heap must be somewhat smaller than that, but let's see :)

**Comment by gavares** [comment]
At least it's giving compile errors now. I'll see about fixing those.

**Comment by gavares** [comment]
I appears this change is likely bigger than I expected. I think that sttp-shared needs to have it's zio version upgraded before tapir can be upgraded. I tried upgrading to the latest sttp-shared which depends on ZIO 2.0.0-RC3 but I'm getting macro errors in `Endpoint.scala` which is a little more than I'm currently able to tackle. I can look into an MR for sttp-shared to upgrade to the latest ZIO version and see how far I can get with that.

**Comment by adamw** [comment]
@gavares sttp-shared 1.3.4 released :)

**Comment by gavares** [comment]
There appear to be some errors compiling macros and I'm a little out of my depth with macros in general. @adamw do you have any intuition about errors like this:
```scala
[error] /Users/ggavares/workspace/tapir/core/src/main/scala/sttp/tapir/EndpointIO.scala:10:19: encountered unrecoverable cycle resolving import.
[error] Note: this is often due in part to a class depending on a definition nested within its companion.
[error] If applicable, you may wish to try moving some members into another object.
[error] import sttp.tapir.macros.{EndpointInputMacros, EndpointOutputMacros, EndpointTransputMacros}
[error]                   ^
[error] /Users/ggavares/workspace/tapir/core/src/main/scala/sttp/tapir/EndpointIO.scala:47:42: not found: type EndpointTransputMacros
[error] sealed trait EndpointTransput[T] extends EndpointTransputMacros[T] {
[error]                                          ^
[error] /Users/ggavares/workspace/tapir/core/src/main/scala/sttp/tapir/Endpoint.scala:9:19: encountered unrecoverable cycle resolving import.
[error] Note: this is often due in part to a class depending on a definition nested within its companion.
[error] If applicable, you may wish to try moving some members into another object.
[error] import sttp.tapir.macros.{EndpointErrorOutputsMacros, EndpointInputsMacros, EndpointOutputsMacros, EndpointSecurityInputsMacros}
[error]                   ^
[error] /Users/ggavares/workspace/tapir/core/src/main/scala/sttp/tapir/Endpoint.scala:143:55: not found: type EndpointErrorOutputsMacros
[error] trait EndpointErrorOutputsOps[A, I, E, O, -R] extends EndpointErrorOutputsMacros[A, I, E, O, R] {
[error]                                                       ^
[error] /Users/ggavares/workspace/tapir/core/src/main/scala/sttp/tapir/Endpoint.scala:103:49: not found: type EndpointInputsMacros
[error] trait EndpointInputsOps[A, I, E, O, -R] extends EndpointInputsMacros[A, I, E, O, R] {
[error]                                                 ^
[error] /Users/ggavares/workspace/tapir/core/src/main/scala/sttp/tapir/Endpoint.scala:246:50: not found: type EndpointOutputsMacros
[error] trait EndpointOutputsOps[A, I, E, O, -R] extends EndpointOutputsMacros[A, I, E, O, R] {
[error]                                                  ^
[error] /Users/ggavares/workspace/tapir/core/src/main/scala/sttp/tapir/Endpoint.scala:82:57: not found: type EndpointSecurityInputsMacros
[error] trait EndpointSecurityInputsOps[A, I, E, O, -R] extends EndpointSecurityInputsMacros[A, I, E, O, R] {
[error]                                                         ^
```

**Comment by adamw** [comment]
@gavares yeah this happens when there are changes in `core`, `core/clean` helps :)

**Comment by gavares** [comment]
Yep that fixed it. I realized I also need to upgrade `sttp` to ZIO RC5. Working on a PR for that now.

**Comment by gavares** [comment]
This update is now waiting on: https://github.com/softwaremill/sttp/pull/1410

**Comment by onsoup42** [comment]
@gavares I believe all the dependencies for this has been updated. Will you up date this PR? Otherwise I'd be happy to put up a PR.

**Comment by gavares** [comment]
Hi @onsoup42 , I've pushed up my latest changes. Feel free to help out. I've been working in my spare cycles on this MR but have been a little too busy to give it the attention I'd like the last 4-5 days.

**Comment by gavares** [comment]
I wonder if the updates to zio-cats-interop might be contributing to the issues I'm seeing. Basically the implicit conversion from a ZIO to a Resource isn't being resolved in the test classes.

**Comment by gavares** [comment]
Thanks @adamw 

After reading your `Resource.scoped` change I feel like I really should have thought of that myself.

**Comment by adamw** [comment]
@gavares I didn't as well, that's a tip I got from discord :) though I guess it falls in line nicely with `ZIO.scoped`

**Comment by gavares** [comment]
zio-http R7 released. I'll submit an update in the next couple hours.

**Comment by adamw** [comment]
@gavares zio http is already updated :)

**Comment by gavares** [comment]
You're too fast @adamw  :)

**Comment by gavares** [comment]
Just pushed another change to fix some js compile errors

**Comment by sandeepkota** [comment]
Can't wait for this to be merged, my team is waiting for this is so badly.

**Comment by adamw** [comment]
It's the zio-http4s tests that hang - specifically, the web socket ones. And they only hang, if streaming tests are run beforehand ... this is going to be "fun" to debug ;)

**Comment by gavares** [comment]
Did the zio-http RC7 release have an issue related to websockets as well? This sounds a bit different but websockets seems to cause issues in both.

**Comment by adamw** [comment]
@gavares no, it's only the http4s-zio backend. Must be something in zio/zio-streams/zio-cats-interop 2 as the zio1 version works fine.

**Comment by gavares** [comment]
I split each of the ServerWebsocketTests out so I could run them in isolation. The tests that are failing to terminate are:

- "json client-terminated echo"
- "string server-terminated echo"

They seem to work when run in isolation (no other tests are run via testOnly) but fail when they are included with any other tests in ServerWebsocketTests. All the other tests run just fine when run with the other tests in the class.

**Comment by gavares** [comment]
```scala
package sttp.tapir.server.tests

import cats.effect.IO
import cats.syntax.all._
import io.circe.generic.auto._
import org.scalatest.matchers.should.Matchers._
import sttp.capabilities.{Streams, WebSockets}
import sttp.client3._
import sttp.monad.MonadError
import sttp.tapir._
import sttp.tapir.generic.auto._
import sttp.tapir.json.circe._
import sttp.tapir.server.interceptor.CustomiseInterceptors
import sttp.tapir.server.interceptor.metrics.MetricsRequestInterceptor
import sttp.tapir.server.tests.ServerMetricsTest._
import sttp.tapir.tests.Test
import sttp.tapir.tests.data.Fruit
import sttp.ws.{WebSocket, WebSocketFrame}

abstract class ServerWebSocketTests[F[_], S <: Streams[S], OPTIONS, ROUTE](
    createServerTest: CreateServerTest[F, S with WebSockets, OPTIONS, ROUTE],
    val streams: S
)(implicit
    m: MonadError[F]
) {
  import createServerTest._

  def functionToPipe[A, B](f: A => B): streams.Pipe[A, B]
  def emptyPipe[A, B]: streams.Pipe[A, B]

  private def stringWs = webSocketBody[String, CodecFormat.TextPlain, String, CodecFormat.TextPlain].apply(streams)
  private def stringEcho = functionToPipe((s: String) => s"echo: $s")

  val test1 = testServer(endpoint.out(stringWs), "string client-terminated echo")((_: Unit) => pureResult(stringEcho.asRight[Unit])) {
    (backend, baseUri) =>
      basicRequest
        .response(asWebSocket { (ws: WebSocket[IO]) =>
          for {
            _ <- ws.sendText("test1")
            _ <- ws.sendText("test2")
            m1 <- ws.receiveText()
            m2 <- ws.receiveText()
          } yield List(m1, m2)
        })
        .get(baseUri.scheme("ws"))
        .send(backend)
        .map(_.body shouldBe Right(List("echo: test1", "echo: test2")))
  }

  val test2 = {

    val reqCounter = newRequestCounter[F]
    val resCounter = newResponseCounter[F]
    val metrics = new MetricsRequestInterceptor[F](List(reqCounter, resCounter), Seq.empty)

    testServer(
      endpoint.out(stringWs).name("metrics"),
      interceptors = (ci: CustomiseInterceptors[F, OPTIONS]) => ci.metricsInterceptor(metrics)
    )((_: Unit) => pureResult(stringEcho.asRight[Unit])) { (backend, baseUri) =>
      basicRequest
        .response(asWebSocket { (ws: WebSocket[IO]) =>
          for {
            _ <- ws.sendText("test1")
            m <- ws.receiveText()
          } yield List(m)
        })
        .get(baseUri.scheme("ws"))
        .send(backend)
        .map { r =>
          r.body shouldBe Right(List("echo: test1"))
          reqCounter.metric.value.get() shouldBe 1
          resCounter.metric.value.get() shouldBe 1
        }
    }
  }

  val test3 =
    testServer(endpoint.out(webSocketBody[Fruit, CodecFormat.Json, Fruit, CodecFormat.Json](streams)), "json client-terminated echo")(
      (_: Unit) => pureResult(functionToPipe((f: Fruit) => Fruit(s"echo: ${f.f}")).asRight[Unit])
    ) { (backend, baseUri) =>
      basicRequest
        .response(asWebSocket { (ws: WebSocket[IO]) =>
          for {
            _ <- ws.sendText("""{"f":"apple"}""")
            _ <- ws.sendText("""{"f":"orange"}""")
            m1 <- ws.receiveText()
            m2 <- ws.receiveText()
          } yield List(m1, m2)
        })
        .get(baseUri.scheme("ws"))
        .send(backend)
        .map(_.body shouldBe Right(List("""{"f":"echo: apple"}""", """{"f":"echo: orange"}""")))
    }

  val test4 =
    testServer(
      endpoint.out(webSocketBody[String, CodecFormat.TextPlain, Option[String], CodecFormat.TextPlain](streams)),
      "string server-terminated echo"
    )((_: Unit) =>
      pureResult(functionToPipe[String, Option[String]] {
        case "end" => None
        case msg   => Some(s"echo: $msg")
      }.asRight[Unit])
    ) { (backend, baseUri) =>
      basicRequest
        .response(asWebSocket { (ws: WebSocket[IO]) =>
          for {
            _ <- ws.sendText("test1")
            _ <- ws.sendText("test2")
            _ <- ws.sendText("end")
            m1 <- ws.eitherClose(ws.receiveText())
            m2 <- ws.eitherClose(ws.receiveText())
            m3 <- ws.eitherClose(ws.receiveText())
          } yield List(m1, m2, m3)
        })
        .get(baseUri.scheme("ws"))
        .send(backend)
        .map(
          _.body.map(_.map(_.left.map(_.statusCode))) shouldBe Right(
            List(Right("echo: test1"), Right("echo: test2"), Left(WebSocketFrame.close.statusCode))
          )
        )
    }

  val test5 =
    testServer(
      endpoint.out(webSocketBody[String, CodecFormat.TextPlain, String, CodecFormat.TextPlain](streams)),
      "empty client stream"
    )((_: Unit) => pureResult(emptyPipe.asRight[Unit])) { (backend, baseUri) =>
      basicRequest
        .response(asWebSocketAlways { (ws: WebSocket[IO]) => ws.eitherClose(ws.receiveText()) })
        .get(baseUri.scheme("ws"))
        .send(backend)
        .map(_.body.left.map(_.statusCode) shouldBe Left(WebSocketFrame.close.statusCode))
    }

  val test6 = testServer(
    endpoint
      .in(isWebSocket)
      .errorOut(stringBody)
      .out(stringWs),
    "non web-socket request"
  )(isWS => if (isWS) pureResult(stringEcho.asRight) else pureResult("Not a WS!".asLeft)) { (backend, baseUri) =>
    basicRequest
      .response(asString)
      .get(baseUri.scheme("http"))
      .send(backend)
      .map(_.body shouldBe Left("Not a WS!"))
  }

  /**   
   *   - works: 3
   *   - works: 4
   *   - works: 1,5
   *   - works: 1,2,6
   *   - works: 1,2,5,6
   *   - DOESN't WORK: 1,3
    *  - DOESN't WORK: 1,4
    *  - DOESN'T WORK: 1,2,3
    *  - DOESN'T WORK: 2,3
    *  - DOESN'T WORK: 2,4
    */
  def tests(): List[Test] = List(
//    test1,
//    test2,
//    test3
    test4
//    test5
//    test6
  )

  // TODO: tests for ping/pong (control frames handling)
}
```

**Comment by gavares** [comment]
After adding some logging, it's pretty clear the server is being shutdown before the 2nd read in the the tests mentioned above is executing. If we modify `test3` in my code above to look like this:

```scala
val test3 =
    testServer(endpoint.out(webSocketBody[Fruit, CodecFormat.Json, Fruit, CodecFormat.Json](streams)), "json client-terminated echo")(
      (_: Unit) => pureResult(functionToPipe((f: Fruit) => Fruit(s"echo: ${f.f}")).asRight[Unit])
    ) { (backend, baseUri) =>
      basicRequest
        .response(asWebSocket { (ws: WebSocket[IO]) =>
          for {
            _ <- IO.consoleForIO.println("Sending apple")
            _ <- ws.sendText("""{"f":"apple"}""")
            _ <- IO.consoleForIO.println("Sending orange")
            _ <- ws.sendText("""{"f":"orange"}""")
            _ <- IO.consoleForIO.println("reading apple")
            m1 <- ws.receiveText(false)
            _ <- IO.consoleForIO.println("reading orange")
            m2 <- ws.receiveText()
          } yield List(m1) // List(m1, m2)
        })
        .get(baseUri.scheme("ws"))
        .send(backend)
        .map(_.body shouldBe Right(List("""{"f":"echo: apple"}""", """{"f":"echo: orange"}""")))
    }
```
The logs show the server is shutdown before we log `reading orange`: 

```
Sending apple
Sending orange
reading apple
2022-04-24 14:06:08,823 [scala-execution-context-global-519] DEBUG o.h.b.s.Http1ServerStage$$anon$1 - Shutting down HttpPipeline
2022-04-24 14:06:08,825 [scala-execution-context-global-519] DEBUG o.h.b.s.Http1ServerStage$$anon$1 - Shutting down.
2022-04-24 14:06:08,825 [scala-execution-context-global-519] DEBUG o.http4s.blazecore.IdleTimeoutStage - Stage IdleTimeoutStage sending inbound command: Connected
2022-04-24 14:06:08,825 [scala-execution-context-global-519] DEBUG o.h.blaze.server.WebSocketDecoder - Starting up.
2022-04-24 14:06:08,825 [scala-execution-context-global-519] DEBUG o.h.blaze.server.WebSocketDecoder - Stage WebSocketDecoder sending inbound command: Connected
2022-04-24 14:06:08,825 [scala-execution-context-global-519] DEBUG o.h.blaze.server.WSFrameAggregator - Starting up.
2022-04-24 14:06:08,825 [scala-execution-context-global-519] DEBUG o.h.blaze.server.WSFrameAggregator - Stage WSFrameAggregator sending inbound command: Connected
2022-04-24 14:06:08,827 [scala-execution-context-global-519] DEBUG o.h.b.websocket.Http4sWSStage - Starting up.
reading orange
```

**Comment by adamw** [comment]
Thanks for the debug! :) I've narrowed it down further to running:

```
    import zio.stream.interop.fs2z._
    zio.Runtime.global.unsafeRunSync(
      fs2.Stream("pen pineapple apple pen".getBytes: _*).toZStream().runCollect
    )
```

+ a single web socket test. I think the server isn't shut down prematurely, it's the way http4s logs switching from handling http traffic to handling WS traffic.

**Comment by adamw** [comment]
@gavares I think I minimised it further, see: https://github.com/zio/interop-cats/issues/533

**Pull request merged**
