### PR TITLE
Update zio-http

### PR DESCRIPTION
**Pull request by guizmaii**

### CODE REVIEW

**Comment by adamw** [comment]
The build failure is due to https://github.com/coursier/coursier/issues/2016

Not sure what to do with it yet, though. I'm not a fan of disabling coursier

**Comment by adamw** [comment]
I've disable coursier for the netty dependencies (https://github.com/softwaremill/tapir/pull/1680), maybe this will help

**Comment by guizmaii** [comment]
Thanks @adamw! Will take a look :)

**Comment by guizmaii** [comment]
Sorry Adam but I'll close this PR. The problem seems to be more complicated than expected and would require more time than I can allocate to this task for now.

**Comment by adamw** [comment]
I'll try continuing the work in #1686 :)

**Pull request closed without merging**
